version: '3.8'

name: interviewiq-service-prod
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interviewiq-backend-prod
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}  # External database (Supabase)
      - SECRET_KEY=${SECRET_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - interviewiq-service-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

networks:
  interviewiq-service-network:
    driver: bridge
