"""add_scenarios_table_for_practice_scenarios

Revision ID: 79401189ee87
Revises: 7b15fd9db179
Create Date: 2025-10-15 19:05:54.674176+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "79401189ee87"
down_revision: Union[str, None] = "7b15fd9db179"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper functions
    def table_exists(table_name):
        try:
            return table_name in inspector.get_table_names()
        except Exception:
            return False
    
    def index_exists(table_name, index_name):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            return index_name in indexes
        except Exception:
            return False
    
    # Create scenarios table if it doesn't exist
    if not table_exists("scenarios"):
        op.create_table(
            "scenarios",
            sa.Column("id", sa.String(length=100), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("category", sa.String(length=100), nullable=True),
            sa.Column("difficulty_level", sa.String(length=20), nullable=False),
            sa.Column("compatible_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column("question_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("usage_count", sa.Integer(), nullable=False),
            sa.Column("average_rating", sa.Float(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    
    # Create indexes if they don't exist
    if table_exists("scenarios"):
        if not index_exists("scenarios", "ix_scenarios_category"):
            op.create_index(op.f("ix_scenarios_category"), "scenarios", ["category"], unique=False)
        if not index_exists("scenarios", "ix_scenarios_difficulty_level"):
            op.create_index(op.f("ix_scenarios_difficulty_level"), "scenarios", ["difficulty_level"], unique=False)
        if not index_exists("scenarios", "ix_scenarios_is_active"):
            op.create_index(op.f("ix_scenarios_is_active"), "scenarios", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper functions
    def table_exists(table_name):
        try:
            return table_name in inspector.get_table_names()
        except Exception:
            return False
    
    def index_exists(table_name, index_name):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            return index_name in indexes
        except Exception:
            return False
    
    # Drop indexes and table if they exist
    if table_exists("scenarios"):
        if index_exists("scenarios", "ix_scenarios_is_active"):
            try:
                op.drop_index(op.f("ix_scenarios_is_active"), table_name="scenarios")
            except Exception:
                pass
        if index_exists("scenarios", "ix_scenarios_difficulty_level"):
            try:
                op.drop_index(op.f("ix_scenarios_difficulty_level"), table_name="scenarios")
            except Exception:
                pass
        if index_exists("scenarios", "ix_scenarios_category"):
            try:
                op.drop_index(op.f("ix_scenarios_category"), table_name="scenarios")
            except Exception:
                pass
        try:
            op.drop_table("scenarios")
        except Exception:
            pass
    # ### end Alembic commands ###
