"""add_question_database_models_for_phase2

Revision ID: 1ed807d85f64
Revises: 79401189ee87
Create Date: 2025-10-15 22:13:06.009121+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ed807d85f64"
down_revision: Union[str, None] = "79401189ee87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper function
    def index_exists(table_name, index_name):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            return index_name in indexes
        except Exception:
            return False
    
    def column_exists(table_name, column_name):
        try:
            columns = [col['name'] for col in inspector.get_columns(table_name)]
            return column_name in columns
        except Exception:
            return False
    
    # Alter columns if they exist
    if column_exists("questions", "question_metadata"):
        try:
            op.alter_column(
                "questions",
                "question_metadata",
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                server_default=None,
                nullable=False,
            )
        except Exception:
            pass
    
    if column_exists("questions", "usage_count"):
        try:
            op.alter_column(
                "questions",
                "usage_count",
                existing_type=sa.INTEGER(),
                server_default=None,
                nullable=False,
            )
        except Exception:
            pass
    
    if column_exists("questions", "updated_at"):
        try:
            op.alter_column(
                "questions",
                "updated_at",
                existing_type=postgresql.TIMESTAMP(timezone=True),
                nullable=False,
                existing_server_default=sa.text("now()"),
            )
        except Exception:
            pass
    
    # Create indexes only if they don't exist
    if not index_exists("questions", "idx_questions_category"):
        op.create_index(
            "idx_questions_category", "questions", ["category"], unique=False
        )
    if not index_exists("questions", "idx_questions_difficulty"):
        op.create_index(
            "idx_questions_difficulty",
            "questions",
            ["difficulty_level"],
            unique=False,
        )
    if not index_exists("questions", "idx_questions_subcategory") and column_exists("questions", "subcategory"):
        op.create_index(
            "idx_questions_subcategory", "questions", ["subcategory"], unique=False
        )
    if not index_exists("questions", "idx_questions_usage_count"):
        op.create_index(
            "idx_questions_usage_count", "questions", ["usage_count"], unique=False
        )
    if not index_exists("questions", "ix_questions_category"):
        op.create_index(
            op.f("ix_questions_category"), "questions", ["category"], unique=False
        )
    if not index_exists("questions", "ix_questions_difficulty_level"):
        op.create_index(
            op.f("ix_questions_difficulty_level"),
            "questions",
            ["difficulty_level"],
            unique=False,
        )
    if not index_exists("questions", "ix_questions_subcategory") and column_exists("questions", "subcategory"):
        op.create_index(
            op.f("ix_questions_subcategory"),
            "questions",
            ["subcategory"],
            unique=False,
        )
    # Alter scenarios columns if they exist
    if column_exists("scenarios", "difficulty_level"):
        try:
            op.alter_column(
                "scenarios",
                "difficulty_level",
                existing_type=sa.VARCHAR(length=20),
                server_default=None,
                existing_nullable=False,
            )
        except Exception:
            pass
    
    if column_exists("scenarios", "is_active"):
        try:
            op.alter_column(
                "scenarios",
                "is_active",
                existing_type=sa.BOOLEAN(),
                server_default=None,
                existing_nullable=False,
            )
        except Exception:
            pass
    
    if column_exists("scenarios", "usage_count"):
        try:
            op.alter_column(
                "scenarios",
                "usage_count",
                existing_type=sa.INTEGER(),
                server_default=None,
                existing_nullable=False,
            )
        except Exception:
            pass
    
    if column_exists("scenarios", "created_at"):
        try:
            op.alter_column(
                "scenarios",
                "created_at",
                existing_type=postgresql.TIMESTAMP(timezone=True),
                nullable=False,
                existing_server_default=sa.text("now()"),
            )
        except Exception:
            pass
    
    if column_exists("scenarios", "updated_at"):
        try:
            op.alter_column(
                "scenarios",
                "updated_at",
                existing_type=postgresql.TIMESTAMP(timezone=True),
                nullable=False,
                existing_server_default=sa.text("now()"),
            )
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper functions
    def table_exists(table_name):
        try:
            return table_name in inspector.get_table_names()
        except Exception:
            return False
    
    def column_exists(table_name, column_name):
        try:
            columns = [col['name'] for col in inspector.get_columns(table_name)]
            return column_name in columns
        except Exception:
            return False
    
    def index_exists(table_name, index_name):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            return index_name in indexes
        except Exception:
            return False
    
    # Alter scenarios columns if they exist
    if table_exists("scenarios"):
        if column_exists("scenarios", "updated_at"):
            try:
                op.alter_column(
                    "scenarios",
                    "updated_at",
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text("now()"),
                )
            except Exception:
                pass
        if column_exists("scenarios", "created_at"):
            try:
                op.alter_column(
                    "scenarios",
                    "created_at",
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text("now()"),
                )
            except Exception:
                pass
        if column_exists("scenarios", "usage_count"):
            try:
                op.alter_column(
                    "scenarios",
                    "usage_count",
                    existing_type=sa.INTEGER(),
                    server_default=sa.text("0"),
                    existing_nullable=False,
                )
            except Exception:
                pass
        if column_exists("scenarios", "is_active"):
            try:
                op.alter_column(
                    "scenarios",
                    "is_active",
                    existing_type=sa.BOOLEAN(),
                    server_default=sa.text("true"),
                    existing_nullable=False,
                )
            except Exception:
                pass
        if column_exists("scenarios", "difficulty_level"):
            try:
                op.alter_column(
                    "scenarios",
                    "difficulty_level",
                    existing_type=sa.VARCHAR(length=20),
                    server_default=sa.text("'medium'::character varying"),
                    existing_nullable=False,
                )
            except Exception:
                pass
    
    # Drop indexes if they exist
    if table_exists("questions"):
        if index_exists("questions", "ix_questions_subcategory"):
            try:
                op.drop_index(op.f("ix_questions_subcategory"), table_name="questions")
            except Exception:
                pass
        if index_exists("questions", "ix_questions_difficulty_level"):
            try:
                op.drop_index(op.f("ix_questions_difficulty_level"), table_name="questions")
            except Exception:
                pass
        if index_exists("questions", "ix_questions_category"):
            try:
                op.drop_index(op.f("ix_questions_category"), table_name="questions")
            except Exception:
                pass
        if index_exists("questions", "idx_questions_usage_count"):
            try:
                op.drop_index("idx_questions_usage_count", table_name="questions")
            except Exception:
                pass
        if index_exists("questions", "idx_questions_subcategory"):
            try:
                op.drop_index("idx_questions_subcategory", table_name="questions")
            except Exception:
                pass
        if index_exists("questions", "idx_questions_difficulty"):
            try:
                op.drop_index("idx_questions_difficulty", table_name="questions")
            except Exception:
                pass
        if index_exists("questions", "idx_questions_category"):
            try:
                op.drop_index("idx_questions_category", table_name="questions")
            except Exception:
                pass
        
        # Alter columns if they exist
        if column_exists("questions", "updated_at"):
            try:
                op.alter_column(
                    "questions",
                    "updated_at",
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text("now()"),
                )
            except Exception:
                pass
        if column_exists("questions", "usage_count"):
            try:
                op.alter_column(
                    "questions",
                    "usage_count",
                    existing_type=sa.INTEGER(),
                    server_default=sa.text("0"),
                    nullable=True,
                )
            except Exception:
                pass
        if column_exists("questions", "question_metadata"):
            try:
                op.alter_column(
                    "questions",
                    "question_metadata",
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    server_default=sa.text("'{}'::jsonb"),
                    nullable=True,
                )
            except Exception:
                pass
    # ### end Alembic commands ###
