"""fix_json_indexes_for_postgresql

Revision ID: f73a0d61689a
Revises: 1ed807d85f64
Create Date: 2025-10-15 22:14:13.467602+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f73a0d61689a"
down_revision: Union[str, None] = "1ed807d85f64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
