"""add_question_database_models_for_phase2

Revision ID: 1ed807d85f64
Revises: 79401189ee87
Create Date: 2025-10-15 22:13:06.009121+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ed807d85f64"
down_revision: Union[str, None] = "79401189ee87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions",
        "question_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "questions",
        "usage_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "questions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "idx_questions_category", "questions", ["category"], unique=False
    )
    op.create_index(
        "idx_questions_difficulty",
        "questions",
        ["difficulty_level"],
        unique=False,
    )
    op.create_index(
        "idx_questions_subcategory", "questions", ["subcategory"], unique=False
    )
    op.create_index(
        "idx_questions_usage_count", "questions", ["usage_count"], unique=False
    )
    op.create_index(
        op.f("ix_questions_category"), "questions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_questions_difficulty_level"),
        "questions",
        ["difficulty_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questions_subcategory"),
        "questions",
        ["subcategory"],
        unique=False,
    )
    op.alter_column(
        "scenarios",
        "difficulty_level",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "scenarios",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "scenarios",
        "usage_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "scenarios",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "scenarios",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scenarios",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "scenarios",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "scenarios",
        "usage_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "scenarios",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "scenarios",
        "difficulty_level",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'medium'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_questions_subcategory"), table_name="questions")
    op.drop_index(
        op.f("ix_questions_difficulty_level"), table_name="questions"
    )
    op.drop_index(op.f("ix_questions_category"), table_name="questions")
    op.drop_index("idx_questions_usage_count", table_name="questions")
    op.drop_index("idx_questions_subcategory", table_name="questions")
    op.drop_index("idx_questions_difficulty", table_name="questions")
    op.drop_index("idx_questions_category", table_name="questions")
    op.alter_column(
        "questions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "questions",
        "usage_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        nullable=True,
    )
    op.alter_column(
        "questions",
        "question_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        nullable=True,
    )
    # ### end Alembic commands ###
