"""Add question bank foundation with global questions and session questions

Revision ID: 7b15fd9db179
Revises: 84cb1aaf7a64
Create Date: 2025-10-14 08:49:51.393175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b15fd9db179'
down_revision: Union[str, None] = '84cb1aaf7a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper functions
    def table_exists(table_name):
        try:
            return table_name in inspector.get_table_names()
        except Exception:
            return False
    
    def column_exists(table_name, column_name):
        try:
            columns = [col['name'] for col in inspector.get_columns(table_name)]
            return column_name in columns
        except Exception:
            return False
    
    def index_exists(table_name, index_name):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            return index_name in indexes
        except Exception:
            return False
    
    def constraint_exists(table_name, constraint_name):
        try:
            constraints = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
            return constraint_name in constraints
        except Exception:
            return False
    
    # Create session_questions table if it doesn't exist
    # Only create if both referenced tables exist
    if not table_exists('session_questions'):
        if table_exists('questions') and table_exists('interview_sessions'):
            op.create_table('session_questions',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('session_id', sa.UUID(), nullable=False),
            sa.Column('question_id', sa.UUID(), nullable=False),
            sa.Column('question_order', sa.Integer(), nullable=False),
            sa.Column('session_specific_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
            )
    
    # Create indexes for session_questions if they don't exist
    if table_exists('session_questions'):
        if not index_exists('session_questions', 'idx_session_questions_order'):
            op.create_index('idx_session_questions_order', 'session_questions', ['question_order'], unique=False)
        if not index_exists('session_questions', 'idx_session_questions_question_id'):
            op.create_index('idx_session_questions_question_id', 'session_questions', ['question_id'], unique=False)
        if not index_exists('session_questions', 'idx_session_questions_session_id'):
            op.create_index('idx_session_questions_session_id', 'session_questions', ['session_id'], unique=False)
        if not index_exists('session_questions', 'ix_session_questions_question_id'):
            op.create_index(op.f('ix_session_questions_question_id'), 'session_questions', ['question_id'], unique=False)
        if not index_exists('session_questions', 'ix_session_questions_session_id'):
            op.create_index(op.f('ix_session_questions_session_id'), 'session_questions', ['session_id'], unique=False)
    
    # Add columns to questions table if they don't exist
    if table_exists('questions'):
        if not column_exists('questions', 'question_metadata'):
            op.add_column('questions', sa.Column('question_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")))
        if not column_exists('questions', 'subcategory'):
            op.add_column('questions', sa.Column('subcategory', sa.String(length=100), nullable=True))
        if not column_exists('questions', 'compatible_roles'):
            op.add_column('questions', sa.Column('compatible_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        if not column_exists('questions', 'required_skills'):
            op.add_column('questions', sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        if not column_exists('questions', 'industry_tags'):
            op.add_column('questions', sa.Column('industry_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        if not column_exists('questions', 'usage_count'):
            op.add_column('questions', sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'))
        if not column_exists('questions', 'average_score'):
            op.add_column('questions', sa.Column('average_score', sa.Float(), nullable=True))
        if not column_exists('questions', 'success_rate'):
            op.add_column('questions', sa.Column('success_rate', sa.Float(), nullable=True))
        if not column_exists('questions', 'ai_service_used'):
            op.add_column('questions', sa.Column('ai_service_used', sa.String(length=50), nullable=True))
        if not column_exists('questions', 'generation_prompt_hash'):
            op.add_column('questions', sa.Column('generation_prompt_hash', sa.String(length=64), nullable=True))
        if not column_exists('questions', 'updated_at'):
            op.add_column('questions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        
        # Alter category column if it exists and is nullable
        if column_exists('questions', 'category'):
            try:
                category_col = next((col for col in inspector.get_columns('questions') if col['name'] == 'category'), None)
                if category_col and category_col.get('nullable', True):
                    op.alter_column('questions', 'category',
                               existing_type=sa.VARCHAR(length=100),
                               nullable=False)
            except Exception:
                pass
        
        # Drop indexes if they exist
        if index_exists('questions', 'idx_questions_session_id'):
            op.drop_index('idx_questions_session_id', table_name='questions')
        if index_exists('questions', 'ix_questions_session_id'):
            op.drop_index('ix_questions_session_id', table_name='questions')
        
        # Create indexes if they don't exist
        if not index_exists('questions', 'idx_questions_category'):
            op.create_index('idx_questions_category', 'questions', ['category'], unique=False)
        if not index_exists('questions', 'idx_questions_difficulty'):
            op.create_index('idx_questions_difficulty', 'questions', ['difficulty_level'], unique=False)
        if not index_exists('questions', 'idx_questions_subcategory') and column_exists('questions', 'subcategory'):
            op.create_index('idx_questions_subcategory', 'questions', ['subcategory'], unique=False)
        if not index_exists('questions', 'idx_questions_usage_count') and column_exists('questions', 'usage_count'):
            op.create_index('idx_questions_usage_count', 'questions', ['usage_count'], unique=False)
        if not index_exists('questions', 'ix_questions_category'):
            op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
        if not index_exists('questions', 'ix_questions_difficulty_level'):
            op.create_index(op.f('ix_questions_difficulty_level'), 'questions', ['difficulty_level'], unique=False)
        if not index_exists('questions', 'ix_questions_subcategory') and column_exists('questions', 'subcategory'):
            op.create_index(op.f('ix_questions_subcategory'), 'questions', ['subcategory'], unique=False)
        
        # Drop foreign key constraint if it exists
        if constraint_exists('questions', 'questions_session_id_fkey'):
            op.drop_constraint('questions_session_id_fkey', 'questions', type_='foreignkey')
        
        # Drop columns if they exist
        if column_exists('questions', 'question_order'):
            op.drop_column('questions', 'question_order')
        if column_exists('questions', 'session_id'):
            op.drop_column('questions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper functions
    def table_exists(table_name):
        try:
            return table_name in inspector.get_table_names()
        except Exception:
            return False
    
    def column_exists(table_name, column_name):
        try:
            columns = [col['name'] for col in inspector.get_columns(table_name)]
            return column_name in columns
        except Exception:
            return False
    
    def index_exists(table_name, index_name):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            return index_name in indexes
        except Exception:
            return False
    
    def constraint_exists(table_name, constraint_name):
        try:
            constraints = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
            return constraint_name in constraints
        except Exception:
            return False
    
    # Drop session_questions table and indexes if they exist
    if table_exists('session_questions'):
        if index_exists('session_questions', 'ix_session_questions_session_id'):
            try:
                op.drop_index(op.f('ix_session_questions_session_id'), table_name='session_questions')
            except Exception:
                pass
        if index_exists('session_questions', 'ix_session_questions_question_id'):
            try:
                op.drop_index(op.f('ix_session_questions_question_id'), table_name='session_questions')
            except Exception:
                pass
        if index_exists('session_questions', 'idx_session_questions_session_id'):
            try:
                op.drop_index('idx_session_questions_session_id', table_name='session_questions')
            except Exception:
                pass
        if index_exists('session_questions', 'idx_session_questions_question_id'):
            try:
                op.drop_index('idx_session_questions_question_id', table_name='session_questions')
            except Exception:
                pass
        if index_exists('session_questions', 'idx_session_questions_order'):
            try:
                op.drop_index('idx_session_questions_order', table_name='session_questions')
            except Exception:
                pass
        try:
            op.drop_table('session_questions')
        except Exception:
            pass
    
    # Restore questions table columns and indexes
    if table_exists('questions'):
        if not column_exists('questions', 'session_id'):
            try:
                op.add_column('questions', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False, server_default=sa.text("'00000000-0000-0000-0000-000000000000'::uuid")))
            except Exception:
                pass
        if not column_exists('questions', 'question_order'):
            try:
                op.add_column('questions', sa.Column('question_order', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
            except Exception:
                pass
        
        if table_exists('interview_sessions') and not constraint_exists('questions', 'questions_session_id_fkey'):
            try:
                op.create_foreign_key('questions_session_id_fkey', 'questions', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
            except Exception:
                pass
        
        # Drop indexes if they exist
        if index_exists('questions', 'ix_questions_subcategory'):
            try:
                op.drop_index(op.f('ix_questions_subcategory'), table_name='questions')
            except Exception:
                pass
        if index_exists('questions', 'ix_questions_difficulty_level'):
            try:
                op.drop_index(op.f('ix_questions_difficulty_level'), table_name='questions')
            except Exception:
                pass
        if index_exists('questions', 'ix_questions_category'):
            try:
                op.drop_index(op.f('ix_questions_category'), table_name='questions')
            except Exception:
                pass
        if index_exists('questions', 'idx_questions_usage_count'):
            try:
                op.drop_index('idx_questions_usage_count', table_name='questions')
            except Exception:
                pass
        if index_exists('questions', 'idx_questions_subcategory'):
            try:
                op.drop_index('idx_questions_subcategory', table_name='questions')
            except Exception:
                pass
        if index_exists('questions', 'idx_questions_difficulty'):
            try:
                op.drop_index('idx_questions_difficulty', table_name='questions')
            except Exception:
                pass
        if index_exists('questions', 'idx_questions_category'):
            try:
                op.drop_index('idx_questions_category', table_name='questions')
            except Exception:
                pass
        
        # Create indexes if they don't exist
        if not index_exists('questions', 'ix_questions_session_id') and column_exists('questions', 'session_id'):
            try:
                op.create_index('ix_questions_session_id', 'questions', ['session_id'], unique=False)
            except Exception:
                pass
        if not index_exists('questions', 'idx_questions_session_id') and column_exists('questions', 'session_id'):
            try:
                op.create_index('idx_questions_session_id', 'questions', ['session_id'], unique=False)
            except Exception:
                pass
        
        # Alter category column if it exists
        if column_exists('questions', 'category'):
            try:
                op.alter_column('questions', 'category',
                           existing_type=sa.VARCHAR(length=100),
                           nullable=True)
            except Exception:
                pass
        
        # Drop columns if they exist
        if column_exists('questions', 'updated_at'):
            op.drop_column('questions', 'updated_at')
        if column_exists('questions', 'generation_prompt_hash'):
            op.drop_column('questions', 'generation_prompt_hash')
        if column_exists('questions', 'ai_service_used'):
            op.drop_column('questions', 'ai_service_used')
        if column_exists('questions', 'success_rate'):
            op.drop_column('questions', 'success_rate')
        if column_exists('questions', 'average_score'):
            op.drop_column('questions', 'average_score')
        if column_exists('questions', 'usage_count'):
            op.drop_column('questions', 'usage_count')
        if column_exists('questions', 'industry_tags'):
            op.drop_column('questions', 'industry_tags')
        if column_exists('questions', 'required_skills'):
            op.drop_column('questions', 'required_skills')
        if column_exists('questions', 'compatible_roles'):
            op.drop_column('questions', 'compatible_roles')
        if column_exists('questions', 'subcategory'):
            op.drop_column('questions', 'subcategory')
        if column_exists('questions', 'question_metadata'):
            op.drop_column('questions', 'question_metadata')
    # ### end Alembic commands ###
