"""Add practice and interview mode support to sessions

Revision ID: 84cb1aaf7a64
Revises: 0179ba46181b
Create Date: 2025-10-13 15:14:14.168335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84cb1aaf7a64'
down_revision: Union[str, None] = '0179ba46181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes if they exist (they may not exist if previous migration didn't create them)
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # Helper to safely drop index if it exists
    def drop_index_if_exists(index_name, table_name):
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
            if index_name in indexes:
                op.drop_index(index_name, table_name=table_name, postgresql_using='gin')
        except Exception:
            # Table or index doesn't exist, skip
            pass
    
    drop_index_if_exists('idx_agent_configuration', 'agent_configurations')
    drop_index_if_exists('idx_analytics_event_data', 'analytics_events')
    drop_index_if_exists('idx_answers_analysis_result', 'answers')
    drop_index_if_exists('idx_answers_multi_agent_scores', 'answers')
    
    # Add new columns with default values
    op.add_column('interview_sessions', sa.Column('mode', sa.String(length=20), nullable=False, server_default='interview'))
    op.add_column('interview_sessions', sa.Column('scenario_id', sa.String(length=100), nullable=True))
    op.add_column('interview_sessions', sa.Column('question_source', sa.String(length=50), nullable=False, server_default='generated'))
    op.add_column('interview_sessions', sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_sessions', sa.Column('job_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Make job_description nullable
    op.alter_column('interview_sessions', 'job_description',
               existing_type=sa.TEXT(),
               nullable=True)
    
    # Drop and recreate indexes
    # Drop index if it exists
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes('interview_sessions')]
        if 'idx_sessions_overall_score' in indexes:
            op.drop_index('idx_sessions_overall_score', table_name='interview_sessions', postgresql_using='gin')
    except Exception:
        # Index doesn't exist, skip
        pass
    op.create_index(op.f('ix_interview_sessions_mode'), 'interview_sessions', ['mode'], unique=False)
    op.create_index(op.f('ix_interview_sessions_scenario_id'), 'interview_sessions', ['scenario_id'], unique=False)
    
    # Remove server defaults after adding columns
    op.alter_column('interview_sessions', 'mode', server_default=None)
    op.alter_column('interview_sessions', 'question_source', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_scenario_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_mode'), table_name='interview_sessions')
    op.create_index('idx_sessions_overall_score', 'interview_sessions', ['overall_score'], unique=False, postgresql_using='gin')
    op.alter_column('interview_sessions', 'job_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('interview_sessions', 'job_context')
    op.drop_column('interview_sessions', 'question_ids')
    op.drop_column('interview_sessions', 'question_source')
    op.drop_column('interview_sessions', 'scenario_id')
    op.drop_column('interview_sessions', 'mode')
    op.create_index('idx_answers_multi_agent_scores', 'answers', ['multi_agent_scores'], unique=False, postgresql_using='gin')
    op.create_index('idx_answers_analysis_result', 'answers', ['analysis_result'], unique=False, postgresql_using='gin')
    op.create_index('idx_analytics_event_data', 'analytics_events', ['event_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_agent_configuration', 'agent_configurations', ['configuration'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
