"""Add practice and interview mode support to sessions

Revision ID: 84cb1aaf7a64
Revises: 0179ba46181b
Create Date: 2025-10-13 15:14:14.168335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84cb1aaf7a64'
down_revision: Union[str, None] = '0179ba46181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_configuration', table_name='agent_configurations', postgresql_using='gin')
    op.drop_index('idx_analytics_event_data', table_name='analytics_events', postgresql_using='gin')
    op.drop_index('idx_answers_analysis_result', table_name='answers', postgresql_using='gin')
    op.drop_index('idx_answers_multi_agent_scores', table_name='answers', postgresql_using='gin')
    
    # Add new columns with default values
    op.add_column('interview_sessions', sa.Column('mode', sa.String(length=20), nullable=False, server_default='interview'))
    op.add_column('interview_sessions', sa.Column('scenario_id', sa.String(length=100), nullable=True))
    op.add_column('interview_sessions', sa.Column('question_source', sa.String(length=50), nullable=False, server_default='generated'))
    op.add_column('interview_sessions', sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_sessions', sa.Column('job_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Make job_description nullable
    op.alter_column('interview_sessions', 'job_description',
               existing_type=sa.TEXT(),
               nullable=True)
    
    # Drop and recreate indexes
    op.drop_index('idx_sessions_overall_score', table_name='interview_sessions', postgresql_using='gin')
    op.create_index(op.f('ix_interview_sessions_mode'), 'interview_sessions', ['mode'], unique=False)
    op.create_index(op.f('ix_interview_sessions_scenario_id'), 'interview_sessions', ['scenario_id'], unique=False)
    
    # Remove server defaults after adding columns
    op.alter_column('interview_sessions', 'mode', server_default=None)
    op.alter_column('interview_sessions', 'question_source', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_scenario_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_mode'), table_name='interview_sessions')
    op.create_index('idx_sessions_overall_score', 'interview_sessions', ['overall_score'], unique=False, postgresql_using='gin')
    op.alter_column('interview_sessions', 'job_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('interview_sessions', 'job_context')
    op.drop_column('interview_sessions', 'question_ids')
    op.drop_column('interview_sessions', 'question_source')
    op.drop_column('interview_sessions', 'scenario_id')
    op.drop_column('interview_sessions', 'mode')
    op.create_index('idx_answers_multi_agent_scores', 'answers', ['multi_agent_scores'], unique=False, postgresql_using='gin')
    op.create_index('idx_answers_analysis_result', 'answers', ['analysis_result'], unique=False, postgresql_using='gin')
    op.create_index('idx_analytics_event_data', 'analytics_events', ['event_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_agent_configuration', 'agent_configurations', ['configuration'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
